# Generated by Django 5.1.6 on 2025-04-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_userprofile_followed_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtask',
            name='button_url',
            field=models.URLField(blank=True, help_text='URL for the task button (e.g., https://twitter.com/yourpage)', null=True),
        ),
    ]
