# Generated by Django 5.1.6 on 2025-04-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_coinpurchaserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coin_balance',
            field=models.PositiveIntegerField(default=0, help_text="User's coin balance."),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Coin Purchase'), ('convert', 'Points to Coin'), ('earn', 'Earned Points'), ('spend', 'Spent Points'), ('other', 'Other')], max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('points', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
